name: domez
description: A new Flutter project.

publish_to: 'none'

version: 1.0.34+34

environment:
  sdk: '>=2.18.0<3.0.0'


dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter:
  geolocator:
  google_fonts: ^4.0.4
  auto_size_text: ^3.0.0
  get:
  gap:
  get_storage:
  google_sign_in:
  font_awesome_flutter:
  share_plus: ^4.0.9
  fluttertoast: ^8.0.9
  connectivity_plus:
  device_info_plus: ^3.2.4
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  geocoding: ^2.0.5
  google_place: ^0.4.7
  flutter_statusbarcolor_ns: ^0.4.0
  flutter_svg: ^1.1.5
  page_indicator:
  intl:
  flutter_calendar_carousel: ^2.4.0
  ticket_widget: ^0.0.1
  avatar_stack: ^1.1.2
  flutter_echarts: ^2.4.0
  dotted_line: ^3.1.0
  rflutter_alert: ^2.0.4
  flutter_facebook_auth:
  cached_network_image:
  firebase_auth:
  firebase_core: ^2.10.0
  sign_in_with_apple:
  pin_code_text_field: ^1.8.0
  http:
  flutter_launcher_icons: ^0.10.0
  flutter_credit_card: ^3.0.4
  pay:
  flutter_stripe:
  internet_connection_checker:
  lottie:
  url_launcher:
  intl_phone_field:
  flutter_rating_stars: ^1.0.3+4
  image_picker:
  firebase_messaging:
  flutter_local_notifications: ^11.0.0
  permission_handler:
  image_compression_flutter:
  image_compression:
  image_gallery_saver: ^1.7.1
  go_router:
  firebase_dynamic_links:
  flutter_html:
dependency_overrides:
firebase_dynamic_links_platform_interface:
git:
url: https://github.com/defiq-dev/flutterfire
ref: fix-type-cast-issue-in-dynamic-link-handling
path: packages/firebase_dynamic_links/firebase_dynamic_links_platform_interface


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/domeLogo.png"


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/images/
    - lottie/no_internet_lottie.json
